plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.nagopy.android.yoursystemisuptodate"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 4
        versionName "1.1.2"
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace "com.nagopy.android.yoursystemisuptodate"
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
